### ISSUE TITLE
Generated Components.yml contains duplicate language in Keywords - invalid YAML

### ISSUE THREAD

**Issue by robert-ancell** [ximion/appstream-generator#92]
The components file in Ubuntu (`/var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_hirsute_main_dep11_Components-amd64.yml.gz`) fails YAML parsing due to containing duplicate languages in the Keywords mapping.

Specifically the first entry fails:
```
---
File: DEP-11
Version: '0.12'
Origin: ubuntu-hirsute-main
MediaBaseUrl: https://appstream.ubuntu.com/media/hirsute
Time: 20210422T135021
---
Type: desktop-application
ID: software-properties-gtk.desktop
Package: software-properties-gtk
...
Keywords:
  de_AT:
  - Treiber
  - Paketquellen
  - Paketquelle
  - PPA
  ca_ES:
  - controladors
  - dipòsits
  - dipòsit
  - ppa
  - orígens
  - programari
...
  ca_AD:
  - controladors
  - dipòsits
  - dipòsit
  - ppa
  - orígens
  - programari
  ca_ES:
  - controladors
  - dipòsits
  - dipòsit
  - ppa
  - fonts
  - programari
```

The YAML specification states:

> The content of a mapping node is an unordered set of key: value node pairs, with the restriction that each of the keys is unique
